language: c
compiler:
    - gcc
    - clang

install:
    - sudo apt-get install liblua5.1-0-dev
    - sudo apt-get install automake
    - sudo apt-get install libncurses5-dev 

# Change this to your needs
script: ./configure && make
