language: c
os:
    - linux
    - osx
compiler:
    - gcc
    - clang
before_install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew update; fi
install:
    - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install autoconf automake build-essential debhelper dpkg-dev autotools-dev dh-autoreconf liblua5.1-0-dev libncurses5-dev; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then brew install lua homebrew/dupes/ncurses ; brew doctor ; brew link ncurses --force; fi
script:
    - if [ $TRAVIS_OS_NAME == linux ]; then dpkg-buildpackage ; EC=$?; if [ ${EC} -ne 0 ] && [ ${EC} -ne 1 ]; then false; else true; fi ; fi
    - git clean -xdf
    - autoreconf -vfim
    - if [ $TRAVIS_OS_NAME == linux ]; then ./configure ; fi
    - if [ $TRAVIS_OS_NAME == osx ]; then LDFLAGS="-L/usr/local/opt/ncurses/lib" CPPFLAGS="-I/usr/local/opt/ncurses/include" ./configure; fi
    - make
    - make check
    - make distcheck
    - make dist-binary

#matrix:
#    allow_failures:
#        - os: osx

#deploy:
#    provider: releases
#    api_key:
#        secure: QBPVxUTvcHBH17Fu/WJlCa+CIoR+peB45PTdWyZIBn/VfEtLlemOeCppGBdv4S5WX2C0cygKnvUwfO4J9yXnpTBJ3L2uM9asRaDXzTZ59x1VJGhbyxfZTLtjNtrEheqV+S3dhuYrpE1xbtnyKLoYx8clgnXqGW7tXIMbU7SqwxY=
#    file: 
#          - "heresyrl-0.1.0-x86_64-linux-gnu.tar.gz"
#          - "heresyrl_0.1.0-1_amd64.deb"
#    on:
#        tags: true
