language: c
compiler:
    - gcc
    - clang

install:
    - sudo apt-get install autoconf
    - sudo apt-get install automake
    - sudo apt-get install build-essential
    - sudo apt-get install debhelper
    - sudo apt-get install dpkg-dev
    - sudo apt-get install autotools-dev
    - sudo apt-get install dh-autoreconf
    - sudo apt-get install gengetopt
    - sudo apt-get install liblua5.1-0-dev
    - sudo apt-get install libncurses5-dev 

# Change this to your needs
script:
    - dpkg-buildpackage ; EC=$?; if [ ${EC} -ne 0 ] && [ ${EC} -ne 1 ]; then false; else true; fi
    - git clean -xdf
    - autoreconf -vfim
    - ./configure && make 
    - make distcheck
    - make dist-binary
