#ifndef STATUS_EFFECTS_STATIC_H
#define STATUS_EFFECTS_STATIC_H

#define SE_NR_CRITICAL_HITS_PER_LOCATION (5)

enum se_ids {
    SEID_NONE,

    /* Withdrawls */
    SEID_WITHDRAWL_HEALTH_STIMM,

    /* Stimms */
    SEID_HEALTH_STIMM,
    SEID_DEATH_STIMM,

    /* Weapons */
    SEID_WEAPON_FLAME,
    SEID_WEAPON_FLAME_AREA,

    /* Criticals -- it is required that these are in order! ie. HEAD1 , HEAD2, HEAD3 ... */

    /* Impact Head */
    SEID_GENERAL_CRITICAL_HEAD_1,
    SEID_GENERAL_CRITICAL_HEAD_2,
    SEID_GENERAL_CRITICAL_HEAD_3,
    SEID_GENERAL_CRITICAL_HEAD_4,
    SEID_GENERAL_CRITICAL_HEAD_5,

    /* Impact Chest */
    SEID_GENERAL_CRITICAL_BODY_1,
    SEID_GENERAL_CRITICAL_BODY_2,
    SEID_GENERAL_CRITICAL_BODY_3,
    SEID_GENERAL_CRITICAL_BODY_4,
    SEID_GENERAL_CRITICAL_BODY_5,

    /* Impact Arms */
    SEID_GENERAL_CRITICAL_RARMS_1,
    SEID_GENERAL_CRITICAL_RARMS_2,
    SEID_GENERAL_CRITICAL_RARMS_3,
    SEID_GENERAL_CRITICAL_RARMS_4,
    SEID_GENERAL_CRITICAL_RARMS_5,

    /* Impact Leg */
    SEID_GENERAL_CRITICAL_RLEGS_1,
    SEID_GENERAL_CRITICAL_RLEGS_2,
    SEID_GENERAL_CRITICAL_RLEGS_3,
    SEID_GENERAL_CRITICAL_RLEGS_4,
    SEID_GENERAL_CRITICAL_RLEGS_5,

    /* Impact Arms */
    SEID_GENERAL_CRITICAL_LARMS_1,
    SEID_GENERAL_CRITICAL_LARMS_2,
    SEID_GENERAL_CRITICAL_LARMS_3,
    SEID_GENERAL_CRITICAL_LARMS_4,
    SEID_GENERAL_CRITICAL_LARMS_5,

    /* Impact Leg */
    SEID_GENERAL_CRITICAL_LLEGS_1,
    SEID_GENERAL_CRITICAL_LLEGS_2,
    SEID_GENERAL_CRITICAL_LLEGS_3,
    SEID_GENERAL_CRITICAL_LLEGS_4,
    SEID_GENERAL_CRITICAL_LLEGS_5,

    /*Death*/
    SEID_FATEHEALTH,

    SEID_MAX,
};

#endif /* STATUS_EFFECTS_STATIC_H */
