#ifndef SPECIALQUALITIES_H
#define SPECIALQUALITIES_H

enum weapon_special_quality {
    WPN_SPCQLTY_ACCURATE,    /* Additional +10 to hit when used with the aim action */
    WPN_SPCQLTY_BALANCED,    /* +10 Parry */
    WPN_SPCQLTY_BLAST_1,     /* All within the weapon's blast radius in squares is hit */
    WPN_SPCQLTY_BLAST_2,     /* All within the weapon's blast radius in squares is hit */
    WPN_SPCQLTY_BLAST_3,
    WPN_SPCQLTY_BLAST_4,
    WPN_SPCQLTY_DEFENSIVE,   /* +15 Parry, -10 to hit  */
    WPN_SPCQLTY_FLAME,       /* No BS Test, All in arc take Agility Test or take damage, 2nd Ag. test to avoid catch fire. */
    WPN_SPCQLTY_FLEXIBLE,    /* Cannot be Parried. */
    WPN_SPCQLTY_INACCURATE,  /* No bonus with aim action */
    WPN_SPCQLTY_OVERHEATS,   /* 90+ -> Overheat */
    WPN_SPCQLTY_POWER_FIELD, /* When this is parried, 75% chance to destroy parrying weapon */
    WPN_SPCQLTY_PRIMITIVE,   /* AP doubled, unless armour is also primitive */
    WPN_SPCQLTY_RECHARGE,    /* Fire only every other round */
    WPN_SPCQLTY_RELIABLE,    /* If jam, 10 on 1d10 to actually jam. <I> */
    WPN_SPCQLTY_SCATTER,     /* Point Blank: 2 DoS score another hit, AP doubled at Long and Extreme ranges. */
    WPN_SPCQLTY_SHOCKING,    /* If damage, test Toughness or be stunned. */
    WPN_SPCQLTY_SMOKE,       /* Creates smoke screen 3d10 metres in diameters, lasts 2d10 Rounds. */
    WPN_SPCQLTY_SNARE,       /* Ag. test or be immobilised */
    WPN_SPCQLTY_TEARING,     /* Roll twice, take highest damage */
    WPN_SPCQLTY_TOXIC,       /* if damage, teest toughness -5 for every damage taken. if failed, take 1d10 extra impact damage. */
    WPN_SPCQLTY_UNARMED,     /* 1d5-3 +Str, Armour doubles */
    WPN_SPCQLTY_UNBALANCED,  /* -10 when parry */
    WPN_SPCQLTY_UNRELIABLE,  /* jams on 90+ */
    WPN_SPCQLTY_UNSTABLE,    /* on hit, roll 1d10: 1: half dmg, 2-9: normal, 10: double damage */
    WPN_SPCQLTY_UNWIELDY,    /* Cannot be used to parry. */
    WPN_SPCQLTY_MAX,
};

enum wearable_special_quality {
    WBL_SPCQLTY_PRIMITIVE, /* AP halved unless weapon is also primitive. */
    WBL_SPCQLTY_MAX,
};

enum weapon_upgrades {
    WPN_UPG_COMPACT,
    WPN_UPG_EXTERMINATOR,
    WPN_UPG_EXTRA_GRIP,
    WPN_UPG_FIRE_SELECTOR,
    WPN_UPG_MELEE_ATTACHMENT,
    WPN_UPG_MONO,
    WPN_UPG_OVERCHARGE_PACK,
    WPN_UPG_RED_DOT,
    WPN_UPG_SILENCER,
    WPN_UPG_TELESCOPE_SIGHT,
    WPN_UPG_MAX,
};

enum ammo_upgrades {
    AMMO_UPG_DUMDUM,     /* +2 dmg, armour doubles */
    AMMO_UPG_HOTSHOT,    /* +1 dmg, tearing, +pen 4, clip_sz == 1, -reliable */
    AMMO_UPG_INFERNO,    /* Ag test or catch fire */
    AMMO_UPG_MANSTOPPER, /* +3 Penetration */
    AMMO_UPG_MAX,
};

enum msr_skill_rate {
    MSR_SKILL_RATE_NONE,
    MSR_SKILL_RATE_BASIC,
    MSR_SKILL_RATE_ADVANCED,
    MSR_SKILL_RATE_EXPERT,
    MSR_SKILL_RATE_MAX,
};

enum msr_skills {
    MSR_SKILLS_AWARENESS,
    MSR_SKILLS_BARTER,
    MSR_SKILLS_CHEM_USE,
    MSR_SKILLS_COMMON_LORE,
    MSR_SKILLS_CONCEALMENT,
    MSR_SKILLS_DEMOLITION,
    MSR_SKILLS_DISGUISE	,
    MSR_SKILLS_DODGE,
    MSR_SKILLS_EVALUATE,
    MSR_SKILLS_FORBIDDEN_LORE,
    MSR_SKILLS_INVOCATION,
    MSR_SKILLS_LOGIC,
    MSR_SKILLS_MEDICAE,
    MSR_SKILLS_PSYSCIENCE,
    MSR_SKILLS_SCHOLASTIC_LORE,
    MSR_SKILLS_SEARCH,
    MSR_SKILLS_SECURITY,
    MSR_SKILLS_SILENT_MOVE,
    MSR_SKILLS_SURVIVAL,
    MSR_SKILLS_TECH_USE,
    MSR_SKILLS_TRACKING,
    MSR_SKILLS_MAX,
};

enum msr_creature_traits {
    CTRTRTS_ARMORPHOUS,
    CTRTRTS_ARMOUR_PLATING,
    CTRTRTS_AUTO_STABILISED,
    CTRTRTS_BESTIAL,
    CTRTRTS_BLIND,
    CTRTRTS_BRUTAL_CHARGE,
    CTRTRTS_CRAWLER,
    CTRTRTS_DAEMONIC,
    CTRTRTS_DARK_SIGHT,
    CTRTRTS_INCOROREAL,
    CTRTRTS_FEAR,
    CTRTRTS_FLYING,
    CTRTRTS_FROM_BEYOND,
    CTRTRTS_HOVERER,
    CTRTRTS_MACHINE,
    CTRTRTS_MULTIPLE_ARMS,
    CTRTRTS_NATURAL_WEAPONS,
    CTRTRTS_PHASE,
    CTRTRTS_POSESSION,
    CTRTRTS_QUADRUPED,
    CTRTRTS_REGENERATION,
    CTRTRTS_SONAR_SENSE,
    CTRTRTS_SOUL_BOUND,
    CTRTRTS_STAMPEDE,
    CTRTRTS_STRANGE_PHYSIOLOGY,
    CTRTRTS_STUFF_OF_NIGHTMARES,
    CTRTRTS_STURDY,
    CTRTRTS_TOXIC,
    CTRTRTS_NATURAL_ARMOUR_1,
    CTRTRTS_NATURAL_ARMOUR_2,
    CTRTRTS_NATURAL_ARMOUR_3,
    CTRTRTS_NATURAL_ARMOUR_4,
    CTRTRTS_UC_STRENGTH_2,
    CTRTRTS_UC_STRENGTH_3,
    CTRTRTS_UC_STRENGTH_4,
    CTRTRTS_UC_AGILITY_2,
    CTRTRTS_UC_AGILITY_3,
    CTRTRTS_UC_AGILITY_4,
    CTRTRTS_UC_TOUGHNESS_2,
    CTRTRTS_UC_TOUGHNESS_3,
    CTRTRTS_UC_TOUGHNESS_4,
    CTRTRTS_UC_INTELLIGIENCE_2,
    CTRTRTS_UC_INTELLIGIENCE_3,
    CTRTRTS_UC_INTELLIGIENCE_4,
    CTRTRTS_UC_WILLPOWER_2,
    CTRTRTS_UC_WILLPOWER_3,
    CTRTRTS_UC_WILLPOWER_4,
    CTRTRTS_UC_FELLOWSHIP_2,
    CTRTRTS_UC_FELLOWSHIP_3,
    CTRTRTS_UC_FELLOWSHIP_4,
    CTRTRTS_UNNATURAL_SPEED,
    CTRTRTS_WARP_INSTABILITY,
    CTRTRTS_WARP_WEAPONS,
    CTRTRTS_MAX,
};

enum msr_talents {
    TLT_NONE,                   /* TLT_NONE is a talent every one has, used to denote talentless weapons */
    TLT_BASIC_WPN_TRNG_BOLT,
    TLT_BASIC_WPN_TRNG_FLAME,
    TLT_BASIC_WPN_TRNG_LAS,
    TLT_BASIC_WPN_TRNG_LAUNCHER,
    TLT_BASIC_WPN_TRNG_MELTA,
    TLT_BASIC_WPN_TRNG_PLASMA,
    TLT_BASIC_WPN_TRNG_PRIMITIVE,
    TLT_BASIC_WPN_TRNG_SP,
    TLT_HEAVY_WPN_TRNG_BOLT,
    TLT_HEAVY_WPN_TRNG_FLAME,
    TLT_HEAVY_WPN_TRNG_LAS,
    TLT_HEAVY_WPN_TRNG_LAUNCHER,
    TLT_HEAVY_WPN_TRNG_MELTA,
    TLT_HEAVY_WPN_TRNG_PLASMA,
    TLT_HEAVY_WPN_TRNG_PRIMITIVE,
    TLT_HEAVY_WPN_TRNG_SP,
    TLT_PISTOL_WPN_TRNG_BOLT,
    TLT_PISTOL_WPN_TRNG_FLAME,
    TLT_PISTOL_WPN_TRNG_LAS,
    TLT_PISTOL_WPN_TRNG_LAUNCHER,
    TLT_PISTOL_WPN_TRNG_MELTA,
    TLT_PISTOL_WPN_TRNG_PLASMA,
    TLT_PISTOL_WPN_TRNG_PRIMITIVE,
    TLT_PISTOL_WPN_TRNG_SP,
    TLT_THROWN_WPN_TRNG_PRIMITIVE,
    TLT_THROWN_WPN_TRNG_CHAIN,
    TLT_THROWN_WPN_TRNG_SHOCK,
    TLT_THROWN_WPN_TRNG_POWER,
    TLT_MELEE_WPN_TRNG_PRIMITIVE,
    TLT_MELEE_WPN_TRNG_CHAIN,
    TLT_MELEE_WPN_TRNG_SHOCK,
    TLT_MELEE_WPN_TRNG_POWER,
    TLT_RESISTANCE_COLD,
    TLT_RESISTANCE_HEAT,
    TLT_RESISTANCE_FEAR,
    TLT_RESISTANCE_POISON,
    TLT_RESISTANCE_WARP,
    TLT_HATRED_FACTION_CRIMINALS,
    TLT_HATRED_FACTION_DAEMONS,
    TLT_HATRED_FACTION_ORKS,
    TLT_HATRED_FACTION_TYRANIDS,
    TLT_HATRED_FACTION_PSYKERS,
    TLT_HATRED_FACTION_HERETICS,
    TLT_HATRED_FACTION_MUTANTS,
    TLT_EXOTIC_WPN_TRNG_NEEDLE_PISTOL,
    TLT_EXOTIC_WPN_TRNG_WEB_PISTOL,
    TLT_EXOTIC_WPN_TRNG_NEEDLE_RIFLE,
    TLT_EXOTIC_WPN_TRNG_WEBBER,
    TLT_PSY_RATING_1,
    TLT_PSY_RATING_2,
    TLT_PSY_RATING_3,
    TLT_PSY_RATING_4,
    TLT_PSY_RATING_5,
    TLT_PSY_RATING_6,

    TLT_TALENT_AWARENESS,
    TLT_TALENT_BARTER,
    TLT_TALENT_CHEM_USE,
    TLT_TALENT_COMMON_LORE,
    TLT_TALENT_CONCEALMENT,
    TLT_TALENT_DEMOLITION,
    TLT_TALENT_DISGUISE,
    TLT_TALENT_DODGE,
    TLT_TALENT_EVALUATE,
    TLT_TALENT_FORBIDDEN_LORE,
    TLT_TALENT_INVOCATION,
    TLT_TALENT_LOGIC,
    TLT_TALENT_MEDICAE,
    TLT_TALENT_PSYSCIENCE,
    TLT_TALENT_SCHOLASTIC_LORE,
    TLT_TALENT_SEARCH,
    TLT_TALENT_SECURITY,
    TLT_TALENT_SILENT_MOVE,
    TLT_TALENT_SURVIVAL,
    TLT_TALENT_TECH_USE,
    TLT_AMBIDEXTROUS,
    TLT_ARMOUR_OF_CONTEMPT,
    TLT_ARMS_MASTER,
    TLT_ASSASSIN_STRIKE,
    TLT_AUTOSANGUINE,
    TLT_BATTLE_RAGE,
    TLT_BLADE_MASTER,
    TLT_BLIND_FIGHTING,
    TLT_BULGING_BICEPS,
    TLT_CLEANSE_AND_PURIFY,
    TLT_COMBAT_MASTER,
    TLT_CORPUS_CONVERSION,
    TLT_COUNTER_ATTACK,
    TLT_CRACK_SHOT,
    TLT_DARK_SOUL,
    TLT_DEADEYE_SHOT,
    TLT_DEFLECT_SHOT,
    TLT_DIE_HARD,
    TLT_DISARM,
    TLT_DISCIPLINE_FOCUS,
    TLT_DOUBLE_TEAM,
    TLT_DUAL_SHOT,
    TLT_DUAL_STRIKE,
    TLT_ELECTRICAL_SOCCOUR,
    TLT_ELECTRO_GRAFT_USE,
    TLT_FAVOURED_BY_THE_WARP,
    TLT_FEARLESS,
    TLT_FEEDBACK_SCREECH,
    TLT_FLAGELLANT,
    TLT_FORESIGHT,
    TLT_FRENZY,
    TLT_FURIOUS_ASSAULT,
    TLT_GUN_BLESSING,
    TLT_GUNSLINGER,
    TLT_HARDY,
    TLT_HEIGHTENED_SENSES,
    TLT_INSANELY_FAITHFULL,
    TLT_IRON_JAW,
    TLT_JADED,
    TLT_LIGHTNING_ATTACK,
    TLT_LOGIS_IMPLANT,
    TLT_LUMINEN_CHARGE,
    TLT_MAGLEV_CHARGE,
    TLT_MARKSMEN,
    TLT_MASTER_CHIRUGEON,
    TLT_MECHANDENDRIUSE,
    TLT_MEDITATION,
    TLT_MENTAL_FORTRESS,
    TLT_MENTAL_RAGE,
    TLT_MIGHSHOT,
    TLT_MINOR_PSYCHIC_POWER,
    TLT_NERVES_OF_STEEL,
    TLT_POWER_WELL,
    TLT_PROSANGUINE,
    TLT_QUICK_DRAW,
    TLT_RAPID_RELOAD,
    TLT_SOUND_CONSTITUTION,
    TLT_SPRINT,
    TLT_STEP_ASIDE,
    TLT_STREET_FIGHTING,
    TLT_STRONG_MINDED,
    TLT_SWIFT_ATTACK,
    TLT_TAKE_DOWN,
    TLT_TECHNICAL_KNOCK,
    TLT_TRUE_GRIT,
    TLT_TWO_WEAPON_WIELDER_MELEE,
    TLT_TWO_WEAPON_WIELDER_BALLISTIC,
    TLT_UNSHAKEBLE_FAITH,
    TLT_WALL_OF_STEEL,

    MSR_TALENTS_MAX,        /*MSR_TALENTS_MAX is also used as an eof marker*/
};


#endif /* SPECIALQUALITIES_H */
