#ifndef ITEMS_STATIC_H
#define ITEMS_STATIC_H

#include "items.h"

enum item_ids {
    /* Wearables*/
    ITEM_ID_FLAK_HELMET,
    ITEM_ID_FLAK_GAUNTLETS,
    ITEM_ID_FLAK_LIGHT_COAT,
    ITEM_ID_FLAK_VEST,
    ITEM_ID_FLAK_JACKET,
    ITEM_ID_FLAK_CLOAK,
    ITEM_ID_FLAK_GUARD_ARMOUR,

    /* Tools */
    /* Fixed Items */
    ITEM_ID_FIXED_LIGHT,

    /* Tools */
    ITEM_ID_GLOW_GLOBE, //GLOWGLOBE
    //Screamer
    //Respirator
    //photovisor
    //medipack
    //infra-red goggles
    //filter plugs
    //bio-scanner

    /* Weapons */
    /* Creature Attacks */
    ITEM_ID_HUMAN_UNARMED,
    ITEM_ID_CREATURE_BITE_UNTRAINED,
    ITEM_ID_CREATURE_BITE_TRAINED,

    /* Pistols*/
    ITEM_ID_STUB_AUTOMATIC,
    ITEM_ID_STUB_REVOLVER,
    ITEM_ID_LAS_PISTOL,

    /* Basic weapons */
    ITEM_ID_LAS_GUN,

    /* Thrown */
    ITEM_ID_FRAG_GRENADE,

    /* Ammo */
    ITEM_ID_ARROW,
    ITEM_ID_PISTOL_AMMO_SP,
    ITEM_ID_PISTOL_AMMO_SP_DUMDUM,
    ITEM_ID_PISTOL_AMMO_SP_MANSTOPPER,
    ITEM_ID_PISTOL_AMMO_LAS,
    ITEM_ID_PISTOL_AMMO_PLASMA,
    ITEM_ID_PISTOL_AMMO_MELTA,
    ITEM_ID_PISTOL_AMMO_FLAME,
    ITEM_ID_PISTOL_AMMO_BOLT,
    ITEM_ID_PISTOL_AMMO_SHURIKEN,
    ITEM_ID_BASIC_AMMO_SP,
    ITEM_ID_BASIC_AMMO_SP_DUMDUM,
    ITEM_ID_BASIC_AMMO_SP_MANSTOPPER,
    ITEM_ID_BASIC_AMMO_SHOTGUN,
    ITEM_ID_BASIC_AMMO_LAS,
    ITEM_ID_BASIC_AMMO_PLASMA,
    ITEM_ID_BASIC_AMMO_MELTA,
    ITEM_ID_BASIC_AMMO_FLAME,
    ITEM_ID_BASIC_AMMO_BOLT,
    ITEM_ID_BASIC_AMMO_SHURIKEN,
    ITEM_ID_BASIC_AMMO_GRENADE,
    ITEM_ID_HEAVY_AMMO_SP,
    ITEM_ID_HEAVY_AMMO_LAS,
    ITEM_ID_HEAVY_AMMO_PLASMA,
    ITEM_ID_HEAVY_AMMO_MELTA,
    ITEM_ID_HEAVY_AMMO_FLAME,
    ITEM_ID_HEAVY_AMMO_BOLT,
    ITEM_ID_HEAVY_AMMO_GRENADE,
    ITEM_ID_HEAVY_AMMO_ROCKET,

    /* Last Entry */
    ITEM_ID_MAX,
};

#endif /* ITEMS_STATIC_H */
