#ifndef ITEMS_STATIC_H
#define ITEMS_STATIC_H

#include "items.h"

enum item_ids {
    ITEM_ID_HUMAN_UNARMED,
    ITEM_ID_FIXED_LIGHT,
    ITEM_ID_AVERAGE_TORCH,
    ITEM_ID_AVERAGE_STUB_AUTOMATIC,
    ITEM_ID_AVERAGE_STUB_REVOLVER,
    ITEM_ID_MAX,
};

#endif /* ITEMS_STATIC_H */
