#ifndef CONDITIONS_STATIC_H
#define CONDITIONS_STATIC_H

#define CDN_NR_CRITICAL_HITS_PER_LOCATION (5)

enum cdn_ids {
    CID_NONE,

    /* Withdrawls */
    CID_WITHDRAWL_HEALTH_STIMM,

    /* Stimms */
    CID_HEALTH_STIMM,
    CID_DEATH_STIMM,

    /* Weapons */
    CID_WEAPON_FLAME,

    CID_FATIQUE,

    /* Criticals -- it is required that these are in order! ie. HEAD1 , HEAD2, HEAD3 ... */
    /* Energy Head */
    CID_ENERGY_CRITICAL_HEAD_1,
    CID_ENERGY_CRITICAL_HEAD_2,
    CID_ENERGY_CRITICAL_HEAD_3,
    CID_ENERGY_CRITICAL_HEAD_4,
    CID_ENERGY_CRITICAL_HEAD_5,

    /* Energy Chest */
    CID_ENERGY_CRITICAL_BODY_1,
    CID_ENERGY_CRITICAL_BODY_2,
    CID_ENERGY_CRITICAL_BODY_3,
    CID_ENERGY_CRITICAL_BODY_4,
    CID_ENERGY_CRITICAL_BODY_5,

    /* Energy Arms */
    CID_ENERGY_CRITICAL_RARMS_1,
    CID_ENERGY_CRITICAL_RARMS_2,
    CID_ENERGY_CRITICAL_RARMS_3,
    CID_ENERGY_CRITICAL_RARMS_4,
    CID_ENERGY_CRITICAL_RARMS_5,

    /* Energy Leg */
    CID_ENERGY_CRITICAL_RLEGS_1,
    CID_ENERGY_CRITICAL_RLEGS_2,
    CID_ENERGY_CRITICAL_RLEGS_3,
    CID_ENERGY_CRITICAL_RLEGS_4,
    CID_ENERGY_CRITICAL_RLEGS_5,

    /* Energy Arms */
    CID_ENERGY_CRITICAL_LARMS_1,
    CID_ENERGY_CRITICAL_LARMS_2,
    CID_ENERGY_CRITICAL_LARMS_3,
    CID_ENERGY_CRITICAL_LARMS_4,
    CID_ENERGY_CRITICAL_LARMS_5,

    /* Energy Leg */
    CID_ENERGY_CRITICAL_LLEGS_1,
    CID_ENERGY_CRITICAL_LLEGS_2,
    CID_ENERGY_CRITICAL_LLEGS_3,
    CID_ENERGY_CRITICAL_LLEGS_4,
    CID_ENERGY_CRITICAL_LLEGS_5,

    /* Impact Head */
    CID_IMPACT_CRITICAL_HEAD_1,
    CID_IMPACT_CRITICAL_HEAD_2,
    CID_IMPACT_CRITICAL_HEAD_3,
    CID_IMPACT_CRITICAL_HEAD_4,
    CID_IMPACT_CRITICAL_HEAD_5,

    /* Impact Chest */
    CID_IMPACT_CRITICAL_BODY_1,
    CID_IMPACT_CRITICAL_BODY_2,
    CID_IMPACT_CRITICAL_BODY_3,
    CID_IMPACT_CRITICAL_BODY_4,
    CID_IMPACT_CRITICAL_BODY_5,

    /* Impact Arms */
    CID_IMPACT_CRITICAL_RARMS_1,
    CID_IMPACT_CRITICAL_RARMS_2,
    CID_IMPACT_CRITICAL_RARMS_3,
    CID_IMPACT_CRITICAL_RARMS_4,
    CID_IMPACT_CRITICAL_RARMS_5,

    /* Impact Leg */
    CID_IMPACT_CRITICAL_RLEGS_1,
    CID_IMPACT_CRITICAL_RLEGS_2,
    CID_IMPACT_CRITICAL_RLEGS_3,
    CID_IMPACT_CRITICAL_RLEGS_4,
    CID_IMPACT_CRITICAL_RLEGS_5,

    /* Impact Arms */
    CID_IMPACT_CRITICAL_LARMS_1,
    CID_IMPACT_CRITICAL_LARMS_2,
    CID_IMPACT_CRITICAL_LARMS_3,
    CID_IMPACT_CRITICAL_LARMS_4,
    CID_IMPACT_CRITICAL_LARMS_5,

    /* Impact Leg */
    CID_IMPACT_CRITICAL_LLEGS_1,
    CID_IMPACT_CRITICAL_LLEGS_2,
    CID_IMPACT_CRITICAL_LLEGS_3,
    CID_IMPACT_CRITICAL_LLEGS_4,
    CID_IMPACT_CRITICAL_LLEGS_5,

    /* Rending Head */
    CID_RENDING_CRITICAL_HEAD_1,
    CID_RENDING_CRITICAL_HEAD_2,
    CID_RENDING_CRITICAL_HEAD_3,
    CID_RENDING_CRITICAL_HEAD_4,
    CID_RENDING_CRITICAL_HEAD_5,

    /* Rending Chest */
    CID_RENDING_CRITICAL_BODY_1,
    CID_RENDING_CRITICAL_BODY_2,
    CID_RENDING_CRITICAL_BODY_3,
    CID_RENDING_CRITICAL_BODY_4,
    CID_RENDING_CRITICAL_BODY_5,

    /* Rending Arms */
    CID_RENDING_CRITICAL_RARMS_1,
    CID_RENDING_CRITICAL_RARMS_2,
    CID_RENDING_CRITICAL_RARMS_3,
    CID_RENDING_CRITICAL_RARMS_4,
    CID_RENDING_CRITICAL_RARMS_5,

    /* Rending Leg */
    CID_RENDING_CRITICAL_RLEGS_1,
    CID_RENDING_CRITICAL_RLEGS_2,
    CID_RENDING_CRITICAL_RLEGS_3,
    CID_RENDING_CRITICAL_RLEGS_4,
    CID_RENDING_CRITICAL_RLEGS_5,

    /* Rending Arms */
    CID_RENDING_CRITICAL_LARMS_1,
    CID_RENDING_CRITICAL_LARMS_2,
    CID_RENDING_CRITICAL_LARMS_3,
    CID_RENDING_CRITICAL_LARMS_4,
    CID_RENDING_CRITICAL_LARMS_5,

    /* Rending Leg */
    CID_RENDING_CRITICAL_LLEGS_1,
    CID_RENDING_CRITICAL_LLEGS_2,
    CID_RENDING_CRITICAL_LLEGS_3,
    CID_RENDING_CRITICAL_LLEGS_4,
    CID_RENDING_CRITICAL_LLEGS_5,

    /* Explosive Head */
    CID_EXPLOSIVE_CRITICAL_HEAD_1,
    CID_EXPLOSIVE_CRITICAL_HEAD_2,
    CID_EXPLOSIVE_CRITICAL_HEAD_3,
    CID_EXPLOSIVE_CRITICAL_HEAD_4,
    CID_EXPLOSIVE_CRITICAL_HEAD_5,

    /* Explosive Chest */
    CID_EXPLOSIVE_CRITICAL_BODY_1,
    CID_EXPLOSIVE_CRITICAL_BODY_2,
    CID_EXPLOSIVE_CRITICAL_BODY_3,
    CID_EXPLOSIVE_CRITICAL_BODY_4,
    CID_EXPLOSIVE_CRITICAL_BODY_5,

    /* Explosive Arms */
    CID_EXPLOSIVE_CRITICAL_RARMS_1,
    CID_EXPLOSIVE_CRITICAL_RARMS_2,
    CID_EXPLOSIVE_CRITICAL_RARMS_3,
    CID_EXPLOSIVE_CRITICAL_RARMS_4,
    CID_EXPLOSIVE_CRITICAL_RARMS_5,

    /* Explosive Leg */
    CID_EXPLOSIVE_CRITICAL_RLEGS_1,
    CID_EXPLOSIVE_CRITICAL_RLEGS_2,
    CID_EXPLOSIVE_CRITICAL_RLEGS_3,
    CID_EXPLOSIVE_CRITICAL_RLEGS_4,
    CID_EXPLOSIVE_CRITICAL_RLEGS_5,

    /* Explosive Arms */
    CID_EXPLOSIVE_CRITICAL_LARMS_1,
    CID_EXPLOSIVE_CRITICAL_LARMS_2,
    CID_EXPLOSIVE_CRITICAL_LARMS_3,
    CID_EXPLOSIVE_CRITICAL_LARMS_4,
    CID_EXPLOSIVE_CRITICAL_LARMS_5,

    /* Explosive Leg */
    CID_EXPLOSIVE_CRITICAL_LLEGS_1,
    CID_EXPLOSIVE_CRITICAL_LLEGS_2,
    CID_EXPLOSIVE_CRITICAL_LLEGS_3,
    CID_EXPLOSIVE_CRITICAL_LLEGS_4,
    CID_EXPLOSIVE_CRITICAL_LLEGS_5,

    /*Death*/
    CID_FATEHEALTH,

    CID_MAX,
};

#endif /* CONDITIONS_STATIC_H */
