#ifndef CONDITIONS_STATIC_H
#define CONDITIONS_STATIC_H

enum cdn_ids {
    CID_NONE,

    /* Withdrawls */
    CID_WITHDRAWL_HEALTH_STIMM,

    /* Stimms */
    CID_HEALTH_STIMM,
    CID_DEATH_STIMM,

    /* Weapons */
    CID_WEAPON_FLAME,

    /* Criticals -- it is required that these are in order! ie. HEAD1 , HEAD2, HEAD3 ... */
    /* Energy Head */
    CID_ENERGY_CRITICAL_HEAD_1,
    CID_ENERGY_CRITICAL_HEAD_2,
    CID_ENERGY_CRITICAL_HEAD_3,
    CID_ENERGY_CRITICAL_HEAD_4,
    CID_ENERGY_CRITICAL_HEAD_5,
    CID_ENERGY_CRITICAL_HEAD_6,
    CID_ENERGY_CRITICAL_HEAD_7,
    CID_ENERGY_CRITICAL_HEAD_8,
    CID_ENERGY_CRITICAL_HEAD_9,

    /* Energy Chest */
    CID_ENERGY_CRITICAL_CHEST_1,
    CID_ENERGY_CRITICAL_CHEST_2,
    CID_ENERGY_CRITICAL_CHEST_3,
    CID_ENERGY_CRITICAL_CHEST_4,
    CID_ENERGY_CRITICAL_CHEST_5,
    CID_ENERGY_CRITICAL_CHEST_6,
    CID_ENERGY_CRITICAL_CHEST_7,
    CID_ENERGY_CRITICAL_CHEST_8,
    CID_ENERGY_CRITICAL_CHEST_9,

    /* Energy Arms */
    CID_ENERGY_CRITICAL_ARMS_1,
    CID_ENERGY_CRITICAL_ARMS_2,
    CID_ENERGY_CRITICAL_ARMS_3,
    CID_ENERGY_CRITICAL_ARMS_4,
    CID_ENERGY_CRITICAL_ARMS_5,
    CID_ENERGY_CRITICAL_ARMS_6,
    CID_ENERGY_CRITICAL_ARMS_7,
    CID_ENERGY_CRITICAL_ARMS_8,
    CID_ENERGY_CRITICAL_ARMS_9,

    /* Energy Leg */
    CID_ENERGY_CRITICAL_LEGS_1,
    CID_ENERGY_CRITICAL_LEGS_2,
    CID_ENERGY_CRITICAL_LEGS_3,
    CID_ENERGY_CRITICAL_LEGS_4,
    CID_ENERGY_CRITICAL_LEGS_5,
    CID_ENERGY_CRITICAL_LEGS_6,
    CID_ENERGY_CRITICAL_LEGS_7,
    CID_ENERGY_CRITICAL_LEGS_8,
    CID_ENERGY_CRITICAL_LEGS_9,

    /* Impact Head */
    CID_IMPACT_CRITICAL_HEAD_1,
    CID_IMPACT_CRITICAL_HEAD_2,
    CID_IMPACT_CRITICAL_HEAD_3,
    CID_IMPACT_CRITICAL_HEAD_4,
    CID_IMPACT_CRITICAL_HEAD_5,
    CID_IMPACT_CRITICAL_HEAD_6,
    CID_IMPACT_CRITICAL_HEAD_7,
    CID_IMPACT_CRITICAL_HEAD_8,
    CID_IMPACT_CRITICAL_HEAD_9,

    /* Impact Chest */
    CID_IMPACT_CRITICAL_CHEST_1,
    CID_IMPACT_CRITICAL_CHEST_2,
    CID_IMPACT_CRITICAL_CHEST_3,
    CID_IMPACT_CRITICAL_CHEST_4,
    CID_IMPACT_CRITICAL_CHEST_5,
    CID_IMPACT_CRITICAL_CHEST_6,
    CID_IMPACT_CRITICAL_CHEST_7,
    CID_IMPACT_CRITICAL_CHEST_8,
    CID_IMPACT_CRITICAL_CHEST_9,

    /* Impact Arms */
    CID_IMPACT_CRITICAL_ARMS_1,
    CID_IMPACT_CRITICAL_ARMS_2,
    CID_IMPACT_CRITICAL_ARMS_3,
    CID_IMPACT_CRITICAL_ARMS_4,
    CID_IMPACT_CRITICAL_ARMS_5,
    CID_IMPACT_CRITICAL_ARMS_6,
    CID_IMPACT_CRITICAL_ARMS_7,
    CID_IMPACT_CRITICAL_ARMS_8,
    CID_IMPACT_CRITICAL_ARMS_9,

    /* Impact Leg */
    CID_IMPACT_CRITICAL_LEGS_1,
    CID_IMPACT_CRITICAL_LEGS_2,
    CID_IMPACT_CRITICAL_LEGS_3,
    CID_IMPACT_CRITICAL_LEGS_4,
    CID_IMPACT_CRITICAL_LEGS_5,
    CID_IMPACT_CRITICAL_LEGS_6,
    CID_IMPACT_CRITICAL_LEGS_7,
    CID_IMPACT_CRITICAL_LEGS_8,
    CID_IMPACT_CRITICAL_LEGS_9,

    /* Rending Head */
    CID_RENDING_CRITICAL_HEAD_1,
    CID_RENDING_CRITICAL_HEAD_2,
    CID_RENDING_CRITICAL_HEAD_3,
    CID_RENDING_CRITICAL_HEAD_4,
    CID_RENDING_CRITICAL_HEAD_5,
    CID_RENDING_CRITICAL_HEAD_6,
    CID_RENDING_CRITICAL_HEAD_7,
    CID_RENDING_CRITICAL_HEAD_8,
    CID_RENDING_CRITICAL_HEAD_9,

    /* Rending Chest */
    CID_RENDING_CRITICAL_CHEST_1,
    CID_RENDING_CRITICAL_CHEST_2,
    CID_RENDING_CRITICAL_CHEST_3,
    CID_RENDING_CRITICAL_CHEST_4,
    CID_RENDING_CRITICAL_CHEST_5,
    CID_RENDING_CRITICAL_CHEST_6,
    CID_RENDING_CRITICAL_CHEST_7,
    CID_RENDING_CRITICAL_CHEST_8,
    CID_RENDING_CRITICAL_CHEST_9,

    /* Rending Arms */
    CID_RENDING_CRITICAL_ARMS_1,
    CID_RENDING_CRITICAL_ARMS_2,
    CID_RENDING_CRITICAL_ARMS_3,
    CID_RENDING_CRITICAL_ARMS_4,
    CID_RENDING_CRITICAL_ARMS_5,
    CID_RENDING_CRITICAL_ARMS_6,
    CID_RENDING_CRITICAL_ARMS_7,
    CID_RENDING_CRITICAL_ARMS_8,
    CID_RENDING_CRITICAL_ARMS_9,

    /* Rending Leg */
    CID_RENDING_CRITICAL_LEGS_1,
    CID_RENDING_CRITICAL_LEGS_2,
    CID_RENDING_CRITICAL_LEGS_3,
    CID_RENDING_CRITICAL_LEGS_4,
    CID_RENDING_CRITICAL_LEGS_5,
    CID_RENDING_CRITICAL_LEGS_6,
    CID_RENDING_CRITICAL_LEGS_7,
    CID_RENDING_CRITICAL_LEGS_8,
    CID_RENDING_CRITICAL_LEGS_9,

    /* Explosive Head */
    CID_EXPLOSIVE_CRITICAL_HEAD_1,
    CID_EXPLOSIVE_CRITICAL_HEAD_2,
    CID_EXPLOSIVE_CRITICAL_HEAD_3,
    CID_EXPLOSIVE_CRITICAL_HEAD_4,
    CID_EXPLOSIVE_CRITICAL_HEAD_5,
    CID_EXPLOSIVE_CRITICAL_HEAD_6,
    CID_EXPLOSIVE_CRITICAL_HEAD_7,
    CID_EXPLOSIVE_CRITICAL_HEAD_8,
    CID_EXPLOSIVE_CRITICAL_HEAD_9,

    /* Explosive Chest */
    CID_EXPLOSIVE_CRITICAL_CHEST_1,
    CID_EXPLOSIVE_CRITICAL_CHEST_2,
    CID_EXPLOSIVE_CRITICAL_CHEST_3,
    CID_EXPLOSIVE_CRITICAL_CHEST_4,
    CID_EXPLOSIVE_CRITICAL_CHEST_5,
    CID_EXPLOSIVE_CRITICAL_CHEST_6,
    CID_EXPLOSIVE_CRITICAL_CHEST_7,
    CID_EXPLOSIVE_CRITICAL_CHEST_8,
    CID_EXPLOSIVE_CRITICAL_CHEST_9,

    /* Explosive Arms */
    CID_EXPLOSIVE_CRITICAL_ARMS_1,
    CID_EXPLOSIVE_CRITICAL_ARMS_2,
    CID_EXPLOSIVE_CRITICAL_ARMS_3,
    CID_EXPLOSIVE_CRITICAL_ARMS_4,
    CID_EXPLOSIVE_CRITICAL_ARMS_5,
    CID_EXPLOSIVE_CRITICAL_ARMS_6,
    CID_EXPLOSIVE_CRITICAL_ARMS_7,
    CID_EXPLOSIVE_CRITICAL_ARMS_8,
    CID_EXPLOSIVE_CRITICAL_ARMS_9,

    /* Explosive Leg */
    CID_EXPLOSIVE_CRITICAL_LEGS_1,
    CID_EXPLOSIVE_CRITICAL_LEGS_2,
    CID_EXPLOSIVE_CRITICAL_LEGS_3,
    CID_EXPLOSIVE_CRITICAL_LEGS_4,
    CID_EXPLOSIVE_CRITICAL_LEGS_5,
    CID_EXPLOSIVE_CRITICAL_LEGS_6,
    CID_EXPLOSIVE_CRITICAL_LEGS_7,
    CID_EXPLOSIVE_CRITICAL_LEGS_8,
    CID_EXPLOSIVE_CRITICAL_LEGS_9,
};

#endif /* CONDITIONS_STATIC_H */
