#ifndef MONSTER_STATIC_H
#define MONSTER_STATIC_H

enum msr_ids {
    MID_NONE,

    MID_DUMMY,
    MID_BASIC_DWARF,
    MID_BASIC_ELF,
    MID_BASIC_HALFLING,
    MID_BASIC_HUMAN,
    MID_MAX,
};

#endif /* MONSTER_STATIC_H */
